services:
  tubearr:
    image: ghcr.io/tubearrteam/tubearr:latest
    build: .
    container_name: tubearr
    restart: unless-stopped
    ports:
      - "5075:5075"
    volumes:
      - ./config:/config
      - /path/to/downloads:/downloads
    environment:
      - TZ=America/New_York
      - ConnectionStrings__TubeArr=Data Source=/config/TubeArr.db
