// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TubeArr.Backend.Data;

#nullable disable

namespace TubeArr.Backend.Persistence.Migrations
{
	[DbContext(typeof(TubeArrDbContext))]
	[Migration("20260330120000_AddMediaManagementUseCustomNfos")]
	partial class AddMediaManagementUseCustomNfos
	{
	}
}
