// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TubeArr.Backend.Data;

#nullable disable

namespace TubeArr.Backend.Persistence.Migrations
{
    [DbContext(typeof(TubeArrDbContext))]
    [Migration("20260402091212_AddFileOpsAndDbOpsQueues")]
    partial class AddFileOpsAndDbOpsQueues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TubeArr.Backend.Data.ChannelCustomPlaylistEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelCustomPlaylists");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ChannelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FilterOutLivestreams")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FilterOutShorts")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasShortsTab")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasStreamsTab")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonitorNewItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitorPreset")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PlaylistFolder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistMultiMatchStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaylistMultiMatchStrategyOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundRobinLatestVideoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.CommandQueueJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("Status");

                    b.ToTable("CommandQueueJobs");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.CustomFilterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomFilters");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.DbOpsHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("DbOpsHistory");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.DbOpsQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("DbOpsQueue");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.DownloadHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Date");

                    b.HasIndex("EventType");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("VideoId");

                    b.ToTable("DownloadHistory");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.DownloadQueueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedSecondsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Progress")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Status");

                    b.ToTable("DownloadQueue");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.FFmpegConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FFmpegConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.FileOpsHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("FileOpsHistory");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.FileOpsQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("FileOpsQueue");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ImportExclusionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("ImportExclusions");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ImportListOptionsConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListSyncLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ListSyncTag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportListOptionsConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.MediaManagementConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUnmonitorPreviouslyDownloadedVideos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChmodFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChownGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CopyUsingHardlinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateEmptyChannelFolders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteEmptyFolders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DownloadLibraryThumbnails")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadPropersAndRepacks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableMediaInfo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraFileExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImportExtraFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumFreeSpaceWhenImporting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecycleBin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecycleBinCleanupDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RescanAfterRefresh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptImportPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SetPermissionsLinux")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipFreeSpaceCheckWhenImporting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomNfos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseScriptImport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoTitleRequired")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaManagementConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.MetadataHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("MetadataHistory");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.MetadataQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethodsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CommandQueueJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandQueueJobId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("MetadataQueue");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.NamingConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ColonReplacementFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomColonReplacementFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyVideoFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodicVideoFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MultiVideoStyle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaylistFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RenameVideos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReplaceIllegalCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialsFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardVideoFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamingVideoFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NamingConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.NotificationConnectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationConnections");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.PlaylistEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeasonIndexLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubePlaylistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("YoutubePlaylistId")
                        .IsUnique();

                    b.HasIndex("ChannelId", "SeasonIndex");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.PlaylistVideoEntity", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "VideoId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("VideoId");

                    b.ToTable("PlaylistVideos");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.PlexProviderConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExposeArtworkUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeChildrenByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerboseRequestLogging")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlexProviderConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.QualityProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowHdr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowMuxedFallback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowSdr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedAudioCodecsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedContainersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedVideoCodecsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("DegradeHeightStepsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DegradeOrderJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailIfBelowMinHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FallbackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxFps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataArgs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinFps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuxArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferSeparateStreams")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredAudioCodecsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredContainersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredVideoCodecsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetryForBetterFormats")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetryWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorblockArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeArgs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.RootFolderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RootFolders");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ScheduledTaskRunHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.ToTable("ScheduledTaskRunHistory");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ScheduledTaskStateEntity", b =>
                {
                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastDurationTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskName");

                    b.ToTable("ScheduledTaskStates");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ServerSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnalyticsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationRequired")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupRetention")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BindAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateValidation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsoleLogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaunchBrowser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LogSizeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyBypassFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProxyBypassLocalAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProxyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyHostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxyPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxyUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SslCertPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SslCertPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SslPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateAutomatically")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateMechanism")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateScriptPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.UiConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarWeekColumnHeader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableColorImpairedMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowRelativeDates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UiLanguage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UiConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.VideoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("AirDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AirDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLivestream")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlexEpisodeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlexIndexLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlexPrimaryCustomPlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlexPrimaryPlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlexSeasonIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YouTubeDataApiVideoResourceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UploadDateUtc");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.HasIndex("ChannelId", "PlexSeasonIndex", "PlexEpisodeIndex");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.VideoFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaInfoJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("VideoFiles");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.YouTubeConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiPriorityMetadataItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseYouTubeApi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("YouTubeConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.YtDlpConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookiesExportBrowser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CookiesPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadQueueParallelWorkers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YtDlpConfig");
                });

            modelBuilder.Entity("TubeArr.Backend.Data.ChannelCustomPlaylistEntity", b =>
                {
                    b.HasOne("TubeArr.Backend.Data.ChannelEntity", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TubeArr.Backend.Data.PlaylistVideoEntity", b =>
                {
                    b.HasOne("TubeArr.Backend.Data.PlaylistEntity", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TubeArr.Backend.Data.VideoEntity", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
