// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TubeArr.Backend.Data;

#nullable disable

namespace TubeArr.Backend.Data.Migrations
{
	[DbContext(typeof(TubeArrDbContext))]
	[Migration("20260430181700_AddDownloadQueueByteProgress")]
	partial class AddDownloadQueueByteProgress
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.0");

			modelBuilder.Entity("TubeArr.Backend.Data.DownloadQueueEntity", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<int>("ChannelId")
					.HasColumnType("INTEGER");

				b.Property<string>("AcquisitionMethodsJson")
					.IsRequired()
					.HasColumnType("TEXT");

				b.Property<long?>("DownloadedBytes")
					.HasColumnType("INTEGER");

				b.Property<DateTimeOffset?>("EndedAtUtc")
					.HasColumnType("TEXT");

				b.Property<int?>("EstimatedSecondsRemaining")
					.HasColumnType("INTEGER");

				b.Property<string>("FormatSummary")
					.HasColumnType("TEXT");

				b.Property<string>("LastError")
					.HasColumnType("TEXT");

				b.Property<string>("OutputPath")
					.HasColumnType("TEXT");

				b.Property<double?>("Progress")
					.HasColumnType("REAL");

				b.Property<DateTimeOffset>("QueuedAtUtc")
					.HasColumnType("TEXT");

				b.Property<long?>("SpeedBytesPerSecond")
					.HasColumnType("INTEGER");

				b.Property<DateTimeOffset?>("StartedAtUtc")
					.HasColumnType("TEXT");

				b.Property<string>("Status")
					.IsRequired()
					.HasColumnType("TEXT");

				b.Property<long?>("TotalBytes")
					.HasColumnType("INTEGER");

				b.Property<int>("VideoId")
					.HasColumnType("INTEGER");

				b.HasKey("Id");

				b.HasIndex("ChannelId");

				b.HasIndex("Status");

				b.ToTable("DownloadQueue");
			});
		}
	}
}

