// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TubeArr.Backend.Data;

#nullable disable

namespace TubeArr.Backend.Persistence.Migrations
{
    [DbContext(typeof(TubeArrDbContext))]
    [Migration("20260325000002_AddYtDlpCookiesExportBrowser")]
    partial class AddYtDlpCookiesExportBrowser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TubeArr.Backend.Data.YtDlpConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookiesPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CookiesExportBrowser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YtDlpConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
